export const BUSCAR_EQUIPES = "BUSCAR_EQUIPES";
export const SELECIONAR_EQUIPE = "SELECIONAR_EQUIPE";
export const SALVAR_EQUIPE = "SALVAR_EQUIPE";
export const EXCLUIR_EQUIPE = "EXCLUIR_EQUIPE";
export const LIMPAR_EQUIPE = "LIMPAR_EQUIPE";

export const BUSCAR_ATLETAS = "BUSCAR_ATLETAS";
export const PESQUISAR_POR_CPF = "PESQUISAR_POR_CPF";
export const SELECIONAR_ATLETA = "SELECIONAR_ATLETA";
export const SALVAR_ATLETA = "SALVAR_ATLETA";
export const EXCLUIR_ATLETA = "EXCLUIR_ATLETA";

export const LOGIN_USUARIO = "LOGIN_USUARIO";

export const USER_LOGOUT = "USER_AUTHENTICATED";
export const AUTHENTICATION_FAILED = "USER_AUTHENTICATED";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";

export const ERRO_AO_CONSULTAR_DADOS = "ERRO_AO_CONSULTAR_DADOS";
export const ERRO_AO_CADASTRAR_DADOS = "ERRO_AO_CADASTRAR_DADOS";
